---
title: "exploratory_crash_worksheet"
author: "Conor Tompkins"
date: "4/21/2018"
output: html_document
runtime: shiny
---

#Introduction

#Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

getwd()
```

```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(lubridate)
library(viridis)
library(igraph)
library(gganimate)
library(scales)

theme_set(theme_bw(base_size = 18))

options(scipen = 999, digits = 4)
```

```{r}
my_subtitle <- "Allegheny County crash data 2004-2017"
my_caption <- "@conor_tompkins - Data from WPRDC"
```

##Load data
```{r}
source("scripts/02_factorize_columns.R")
source("scripts/03_clean_data.R")

df <- data %>% 
  mutate(casualty_count = injury_count + fatal_count)
  #arrange(crash_year, crash_month, day_of_week, hour_of_day)

#df %>% 
#  select(crash_year, crash_month, day_of_week, hour_of_day) -> test
rm("data", "df_combined_allegheny_county_crash_data_2004_2017_factorized")
```

This graph shows that the number of crashes per year is stable, with some year-to-year variation.
```{r}
df %>% 
  mutate(crash_year = factor(crash_year)) %>% 
  count(crash_year) %>% 
  ggplot(aes(crash_year, n, group = 1)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(limits = c(0, 13000),
                     label=comma) +
  labs(title = "Crashes per year",
       subtitle = my_subtitle,
       x = NULL,
       y = "Number of crashes",
       caption = my_caption) +
    theme(axis.text.x = element_text(angle = 75, hjust = 1))
```

This shows that the number of crashes per month has varied similarly over the years:
```{r}
df %>% 
  mutate(crash_year = factor(crash_year)) %>% 
  count(crash_year, crash_month) %>% 
  ggplot(aes(crash_month, n)) +
    geom_smooth(aes(group = 1)) +
    geom_jitter(aes(color = crash_month),
                height = 0,
                width = .25,
                alpha = .5,
                show.legend = F) +
    scale_y_continuous(label = comma) +
    scale_color_viridis("Month",
                        discrete = TRUE) +
    labs(title = "Crashes per month",
         subtitle = my_subtitle,
         x = "1 dot = Month/Year. Jitter applied",
         y = "Number of crashes",
         caption = my_caption) +
  theme(axis.title.x = element_text(size = 12))
```

```{r}
df %>% 
  count(crash_year, crash_month, day_of_week) -> df_months_year_dow


df_months_year_dow %>% 
  group_by(day_of_week) %>% 
  summarize(median = median(n)) -> df_dow

df_months_year_dow %>% 
  ggplot(aes(day_of_week, n, color = day_of_week)) +
  geom_jitter(height = 0,
              alpha = .2,
              show.legend = F) +
  geom_point(data = df_dow,
             aes(x = day_of_week,
                 y = median),
             size = 4,
             show.legend = F) +
  scale_color_viridis("Weekday",
                        discrete = TRUE) +
  scale_y_continuous(label = comma) +
  labs(title = "Crashes per weekday",
         subtitle = my_subtitle,
         x = "Large dot = median, small dot = Weekday/Month/Year",
         y = "Number of crashes",
         caption = my_caption) +
  theme(axis.title.x = element_text(size = 12),
        axis.text.x = element_text(size = 12))
```


```{r}
df %>% 
  mutate(crash_month = fct_rev(crash_month)) %>% 
  count(crash_year, crash_month) %>% 
  ggplot(aes(crash_year, crash_month, fill = n)) +
    geom_tile() +
    coord_equal() +
    scale_x_continuous(expand = c(0,0),
                       breaks = c(2004:2017)) +
    scale_y_discrete(expand = c(0,0)) +
    scale_fill_viridis("Number of crashes",
                       labels = comma) +
    labs(title = "Crash heatmap",
         subtitle = my_subtitle,
         x = NULL,
         y = NULL,
         caption = my_caption) +
    theme(panel.grid = element_blank(),
          axis.text.x = element_text(angle = 75, hjust = 1))
```

```{r}
df %>% 
  mutate(day_of_week = fct_rev(day_of_week)) %>% 
  filter(!hour_of_day > 24,
         !is.na(day_of_week)) %>% 
  count(day_of_week, hour_of_day) %>% 
  ggplot(aes(hour_of_day, day_of_week, fill = n)) +
  geom_tile() +
  coord_equal() +
  labs(title = "Crash heatmap",
       subtitle = my_subtitle,
       x = "Hour of day",
       y = "",
       caption = my_caption) +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_viridis(labels = comma,
                     "Number of crashes") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8, 
                                   angle = 300))
```

```{r, fig.show='animate', eval= FALSE}
df %>% 
  arrange(crash_month, day_of_week, hour_of_day) %>% 
  mutate(day_of_week = fct_rev(day_of_week),
         crash_month = factor(crash_month, ordered = FALSE),
         period = fct_inorder(str_c(day_of_week, hour_of_day, sep = "-"))) %>% 
  filter(!hour_of_day > 24,
         !is.na(day_of_week)) %>% 
  count(crash_month, day_of_week, hour_of_day) %>% 
  ggplot(aes(hour_of_day, day_of_week, fill = n, frame = crash_month)) +
  geom_tile() +
  coord_equal() +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_viridis() -> plot1
#plot1
gganimate(plot1, interval = .5)
```

```{r}
df %>% 
  select(day_of_week, time_of_day) %>% 
  filter(!time_of_day > 2400,
         !is.na(day_of_week)) %>% 
  mutate(day_of_week = fct_rev(day_of_week),
         hour = time_of_day %/% 100,
         minute = time_of_day %% 100) %>% 
  count(day_of_week, hour, minute) %>% 
  complete(day_of_week, hour = 0:23, minute = 0:60) %>% 
  replace_na(list(n = 0)) %>% 
  mutate(time = make_datetime(hour = hour, min = minute),
         time = round_date(time, unit = "15 minutes")) %>%
  group_by(day_of_week, time) %>% 
  summarize(n = sum(n)) -> df_time_rounded

df_time_rounded %>% 
  ggplot(aes(time, day_of_week, fill = n)) +
  geom_tile() +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_datetime(date_labels = ("%H:%M"),
                   expand = c(0,0)) +
  scale_fill_viridis("Number of crashes") +
  labs(title = "Crash heatmap",
       subtitle = my_subtitle,
       x = "Time (rounded to nearest 15 minutes)",
       y = "",
       caption = my_caption) +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8, angle = 300))
```

```{r, fig.show='animate', eval= FALSE}
#animate by year, month, and time. cumulative = TRUE so the chart builds left to right
#library(gganimate)
df %>% 
  select(crash_month, day_of_week, time_of_day) %>% 
  filter(!time_of_day > 2400,
         !is.na(day_of_week),
         !is.na(crash_month)) %>% 
  mutate(crash_month = factor(crash_month, ordered = FALSE),
         day_of_week = fct_rev(day_of_week),
         hour = time_of_day %/% 100,
         minute = time_of_day %% 100) %>% 
  count(crash_month, day_of_week, hour, minute) %>% 
  complete(crash_month, day_of_week, hour = 0:23, minute = 0:60) %>% 
  replace_na(list(n = 0)) %>% 
  mutate(time = make_datetime(hour = hour, min = minute),
         time = round_date(time, unit = "15 minutes")) %>%
  group_by(crash_month, day_of_week, time) %>% 
  summarize(n = sum(n)) -> test

test %>% 
  ggplot(aes(time, day_of_week, fill = n, frame = crash_month)) +
  geom_tile() +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_datetime(date_labels = ("%H:%M"),
                   expand = c(0,0)) +
  scale_fill_viridis("Number of crashes") +
  labs(subtitle = "Car accidents in Allegheny County",
       x = "Time (rounded to nearest 15 minutes)",
       y = "",
       caption = "@conor_tompkins, data from WPRDC") -> plot2

#plot2
gganimate(plot2, title_frame = TRUE,  interval = .75, ani.width=1600, ani.height=800, ani.res = 1000)
```

```{r}
df %>%
  select(time_of_day, day_of_week) %>% 
  filter(!time_of_day > 2400,
         !is.na(day_of_week)) %>% 
  mutate(hour = time_of_day %/% 100,
         minute = time_of_day %% 100,
         time = make_datetime(hour = hour, min = minute),
         time = round_date(time, unit = "15 minutes")) %>% 
  ggplot(aes(time, color = day_of_week)) +
  geom_freqpoly(size = 2) +
  scale_color_viridis("Weekday", 
                      discrete = TRUE) +
  scale_x_datetime(labels = date_format("%H:%M")) +
  labs(title = "",
       subtitle = my_subtitle,
       x = "Time (rounded to nearest 15 minutes)",
       y = "Number of crashes",
       caption = my_caption)
```

```{r}
df %>%
  mutate(day_of_week = fct_rev(day_of_week)) %>% 
  filter(hour_of_day < 24) %>% 
  group_by(day_of_week, hour_of_day) %>% 
  summarize(person_sum = sum(person_count, na.rm = TRUE),
            casualties_sum = sum(casualty_count, na.rm = TRUE),
            casualties_per_person = casualties_sum / person_sum) %>% 
  ggplot(aes(hour_of_day, day_of_week, fill = casualties_per_person)) +
  geom_tile() +
  coord_equal() +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_viridis("Casualties per person") +
  labs(title = "",
       subtitle = my_subtitle,
       x = "Hour",
       y = "",
       caption = my_caption) +
  theme(legend.direction = "horizontal",
        legend.position = "bottom",
        legend.text = element_text(size = 8, 
                                   angle = 300))
```


```{r eval = FALSE}
#split this into 2 charts

df %>% 
  select(crash_year, crash_month, person_count, fatal_count, injury_count, unb_death_count, belted_death_count, ped_death_count, bicycle_death_count) %>% 
  arrange(crash_year, crash_month) %>%
  mutate(time_period = make_date(year = crash_year, month = crash_month)) %>% 
  #mutate(crash_year = fct_inorder(as.character(crash_year)),
  #       time_period = str_c(crash_year, crash_month, sep = "-"),
  #       time_period = fct_inorder(time_period)) %>%
  gather(measure, n, -c(crash_year, crash_month, time_period)) %>%
  mutate(measure = factor(measure, 
                          levels = c("person_count", "injury_count", 
                                     "fatal_count", "belted_death_count", 
                                     "unb_death_count", "ped_death_count", "bicycle_death_count"),
                          labels = c("Person count", "Injury count", 
                                     "Fatalities count", "Belted deaths count",
                                     "Unbelted death count", "Pedestrian death count", "Bicycle death count"))) %>% 
  group_by(time_period, crash_year, crash_month, measure) %>% 
  summarize(n = sum(n)) %>% 
  arrange(measure, time_period) %>% 
  group_by(measure) %>% 
  mutate(n_cumulative = cumsum(n)) -> df_cumulative

df_cumulative %>% 
  ggplot(aes(time_period, n_cumulative, color = measure, group = measure)) +
  geom_line(size = 1) +
  facet_wrap(~measure,
             ncol = 3,
             scales = "free_y") +
  scale_color_viridis(discrete = TRUE,
                      guide = FALSE) +
  scale_y_continuous(label = comma) +
  labs(title = "",
       subtitle = my_subtitle,
       x = "Year-Month",
       y = "Cumulative sum",
       caption = my_caption) +
  theme(panel.grid = element_blank())
```

```{r}
df %>% 
  select(crash_year, crash_month, injury_count, fatal_count) %>% 
  gather(measure, value, -c(crash_year, crash_month)) %>% 
  mutate(measure = factor(measure, 
                          levels = c("injury_count", "fatal_count"),
                          labels = c("Injuries", "Fatalities"))) %>% 
  group_by(crash_year, crash_month, measure) %>% 
  summarize(value = sum(value, na.rm = TRUE)) %>% 
  ggplot(aes(crash_month, value, color = crash_month)) +
    geom_jitter(alpha = .75,
                height = 0,
                width = .25,
                show.legend = FALSE) +
    facet_wrap(~measure,
             ncol = 1,
             scales = "free") +
    labs(title = "Injuries and fatalities",
       subtitle = my_subtitle,
       x = NULL,
       y = "Sum")
```


```{r}
df %>% 
  select(crash_year, crash_month, ped_death_count) %>%
  group_by(crash_year, crash_month) %>% 
  summarize(ped_death_count = sum(ped_death_count, na.rm = TRUE)) %>% 
  ggplot(aes(crash_month, ped_death_count, color = crash_month)) +
    geom_jitter(alpha = .75,
                height = .15,
                width = .25,
                show.legend = FALSE) +
    scale_color_viridis("Month",
                      discrete = TRUE) +
    labs(title = "Pedestrian deaths",
       subtitle = my_subtitle,
       x = NULL,
       y = "Sum")
```

```{r}
df %>% 
  select(crash_year, crash_month, belted_death_count, unb_death_count) %>% 
  arrange(crash_year, crash_month) %>%
  mutate(time_period = make_date(year = crash_year, month = crash_month)) %>%
  group_by(time_period, crash_year, crash_month) %>% 
  summarize(belted_death_count = sum(belted_death_count),
            unb_death_count = sum(unb_death_count)) %>% 
  gather(death_type, death_count, -c(time_period, crash_year, crash_month)) %>% 
  arrange(death_type, time_period) %>% 
  group_by(death_type) %>% 
  #group_by(time_period) %>% 
  mutate(death_count_cum = cumsum(death_count)) %>% 
  ungroup() %>% 
  mutate(death_type = factor(death_type,
                             levels = c("belted_death_count", "unb_death_count"),
                             labels = c("Belted deaths", "Unbelted deaths"))) -> df_belted_unbelted

df_belted_unbelted %>% 
  ggplot(aes(time_period, death_count_cum, color = death_type, group = death_type)) +
  geom_line(size = 2) +
  scale_color_viridis("", discrete = TRUE) +
  scale_y_continuous(label = comma) +
  labs(title = "Car occupant fatalities",
       subtitle = my_subtitle,
       x = "",
       y = "Cumulative sum of deaths",
       caption = my_caption) +
  theme(panel.grid = element_blank())
```