---
title: "mapping"
author: "Conor Tompkins"
date: "4/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)

getwd()
```

```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(lubridate)
library(viridis)
library(ggmap)
library(broom)
library(gganimate)

theme_set(theme_bw(base_size = 20))

options(scipen = 999, digits = 4)
```



```{r}
source("scripts/02_factorize_columns.R")
source("scripts/03_clean_data.R")

df <- data
rm("data", "df_combined_allegheny_county_crash_data_2004_2017_factorized")
```


```{r}
map_pgh <- get_map("Pittsburgh, PA",
                   zoom = 10,
                   maptype = "toner",
                   source = "stamen")

map_pgh <- ggmap(map_pgh)
```

```{r}
map_pgh
```

```{r}
df %>% 
  select(dec_lat, dec_long, hour_of_day, day_of_week) %>% 
  filter(!is.na(hour_of_day),
         hour_of_day < 24) %>% 
  #count(hour_of_day, dec_lat, dec_long) %>% 
  filter(!is.na(dec_lat),
         !is.na(dec_long)) -> df_map
```

```{r}
map_pgh +
  stat_density_2d(data = df_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis() +
  theme_void()
```

```{r}
map_pgh +
  stat_density_2d(data = df_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis() +
  facet_wrap(~hour_of_day) +
  theme_void()
```

```{r}
map_pgh +
  stat_density_2d(data = df_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis() +
  facet_wrap(~day_of_week) +
  theme_void()
```

```{r}
df %>% 
  select(dec_lat, dec_long, road_owner) %>% 
  #filter(!is.na(road_owner)) %>% 
  #count(hour_of_day, dec_lat, dec_long) %>% 
  filter(!is.na(dec_lat),
         !is.na(dec_long)) -> df_map_road_owner

map_pgh +
  stat_density_2d(data = df_map_road_owner, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis() +
  theme_void() +
  facet_wrap(~road_owner)
```

```{r}
map_pgh_ani <- get_map("Pittsburgh, PA",
                   zoom = 12,
                   maptype = "toner",
                   source = "stamen")

map_pgh_ani <- ggmap(map_pgh_ani)

#map_pgh_ani +
#  stat_density_2d(data = df_map, 
#                  aes(dec_long, dec_lat,
#                      fill = ..level..),
#                  geom = "polygon",
#                  alpha = .3) +
#  facet_wrap(~hour_of_day) +
#  scale_fill_viridis() +
#  labs(title = "Hour:",
#       subtitle = "Crashes in Allegheny County 2014-2017")

df_map %>% 
  mutate(day_type = case_when(day_of_week %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday") ~ "Weekday",
                              day_of_week %in% c("Saturday", "Sunday") ~ "Weekend")) %>% 
  select(-day_of_week) -> df_map_day_type


map_pgh +
  stat_density_2d(data = df_map_day_type, 
                  aes(dec_long, dec_lat,
                      fill = ..level..,
                      frame = as.factor(hour_of_day)),
                  geom = "polygon",
                  alpha = .3) +
  facet_wrap(~day_type, nrow = 1) +
  scale_fill_viridis("Number of crashes") +
  labs(title = "Hour:",
       subtitle = "Crashes in Allegheny County 2004-2017",
       caption = "@conor_tompkins, data from WPRDC") +
  theme_void() +
  theme(legend.position="bottom",
        legend.direction = "horizontal") -> p
gganimate(p, interval = .5, title_frame = TRUE, ani.width=600, ani.height= 400, ani.res = 500)

gganimate(p, interval = .5, title_frame = TRUE, ani.width=600, ani.height= 400, ani.res = 500, "output.gif")
```