---
title: "modeling_crash_data randomforest"
author: "Conor Tompkins"
date: "April 24, 2018"
output: html_document
---
  
  #Notes
  
  *change crash_year to years_since_2014
*need to deal with cyclical nature of hour
**use sin() and cos()
***xhour = sin(2pi * hour_of_day/24), yhour = cos(2pi * hour_of_day/24)


###SCREWED UP RIGHT NOW, WIP

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = TRUE)
getwd()
```

```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(lubridate)
library(viridis)
library(ggmap)
library(broom)
library(modelr)
library(ranger)
library(rpart)
library(rpart.plot)
library(broomstick)

theme_set(theme_bw(base_size = 18))

options(scipen = 999, digits = 4)
```

```{r}
source("scripts/02_factorize_columns.R")
source("scripts/03_clean_data.R")

df <- data %>% 
  filter(hour_of_day < 24)
rm("data", "df_combined_allegheny_county_crash_data_2004_2017_factorized")
```


```{r}
df %>% 
  summarize_all(funs(sum(is.na(.)) / length(.))) %>% 
  gather(column_name, is_na) %>% 
  arrange(desc(is_na)) %>% 
  filter(is_na >= .1) %>% 
  mutate(column_name = fct_reorder(column_name, is_na)) %>% 
  ggplot(aes(column_name, is_na)) +
  geom_col() +
  coord_flip()

colnames(df)

df %>% 
  select(fatal, crash_year, day_of_week, hour_of_day, weather, illumination, road_condition, collision_type, relation_to_road, intersect_type, tcd_type, location_type, rdwy_surf_type_cd, speed_limit, person_count, automobile_count, motorcycle_count, bus_count, small_truck_count, heavy_truck_count, suv_count, van_count, bicycle_count, ped_count)  %>% 
  mutate(crash_year = crash_year -  2004,
         fatal = as.factor(fatal)) %>% 
  na.omit() -> df_model_1
```

```{r}
crash_rf <- ranger(fatal ~ ., 
                   data = df_model_1,
                   classification = TRUE,
                   importance = "impurity",
                   num.trees = 500)
```
```{r}
importance(crash_rf) %>% 
  tidy() %>% 
  arrange(desc(x)) %>% 
  mutate(names = fct_reorder(names, x)) %>% 
  ggplot(aes(names, x)) +
  geom_col() +
  coord_flip()
summary(crash_rf)
crash_rf$prediction.error
```

#model_1
```{r}
df_model_1 %>% 
  mutate(.pred = predictions(crash_rf)) -> df_model_1_output
```

```{r}
df_model_1 %>% 
  count(fatal, .pred, sort = TRUE) %>% 
  ggplot(aes(fatal, .pred, fill = n)) +
  geom_tile(color = "grey") +
  scale_fill_viridis()
```

```{r}
model_2 <- rpart(fatal ~ ., data = df_model_1)
model_2_output <- as_tibble(predict(model_2, newdata = df_model_1))
df_model_2 %>% 
  bind_cols(model_2_output) %>% 
  rename(pred_non_fatal = `FALSE`,
         pred_fatal = `TRUE`) %>% 
  select(fatal, pred_fatal, pred_non_fatal, everything()) -> df_model_2
df_model_2
rpart.plot(model_2)
tidy(model_2)
summary(model_2)
```
#model_2
```{r}
df %>% 
  select(fatal_count, injury_count, crash_year, day_of_week, hour_of_day, weather, illumination, road_condition, collision_type, relation_to_road, urban_rural, person_count, automobile_count, motorcycle_count, bus, small_truck_count, heavy_truck_count, suv_count, van_count, bicycle_count, ped_count, speed_limit,
         speeding, cell_phone, alcohol_related, drinking_driver, aggressive_driving, fatigue_asleep, running_red_lt, running_stop_sign, tailgating, cross_median, impaired_driver) %>%
  mutate_at(vars(speeding:impaired_driver), as.integer) %>% 
  mutate_at(vars(speeding:impaired_driver), as.logical) %>%
  mutate_if(is.character, factor) %>% 
  mutate_if(is.logical, as.factor) %>% 
  mutate(crash_year = crash_year -  2004,
         casualties = fatal_count + injury_count, 
         person_count_greater_2 = case_when(person_count >= 2 ~ TRUE,
                                             person_count < 1 ~ FALSE),
         person_count_greater_2 = factor(person_count_greater_2)) %>% 
  select(-c(fatal_count, injury_count, person_count)) %>% 
  na.omit() -> df_model_2

glimpse(df_model_2)
```

```{r}
df_model_2 %>% 
  ggplot(aes(casualties)) +
  geom_freqpoly()
```
```{r}
model_2 <- rpart(casualties ~ ., 
                 control = rpart.control(cp = .005),
                 data = df_model_2)
model_2_output <- predict(model_2, newdata = df_model_2)
head(model_2_output)
```
```{r}
df_model_2 %>% 
  mutate(.pred = model_2_output, 
         .resid = .pred - casualties) %>% 
  select(casualties, .pred, .resid, everything()) -> df_model_2
df_model_2
```
```{r}
prp(model_2)
tidy(model_2)
summary(model_2)
```
```{r}
df_model_2 %>% 
  ggplot(aes(casualties, .pred)) +
  geom_jitter(alpha = .1) +
  geom_smooth()
```
```{r}
df_model_2 %>% 
  ggplot(aes(casualties, .resid)) +
  geom_jitter(alpha = .1) +
  geom_smooth() 
```

#model 3
```{r}
df %>% 
  select(fatal_count, injury_count, person_count, crash_year, day_of_week,
         hour_of_day, weather, illumination, road_condition, collision_type,
         relation_to_road, urban_rural, automobile, motorcycle, bus, small_truck,
         heavy_truck, suv, van, bicycle, pedestrian,
         speed_limit, speeding, cell_phone, alcohol_related, drinking_driver,
         aggressive_driving, fatigue_asleep, running_red_lt, running_stop_sign, tailgating,
         cross_median, impaired_driver) %>%
  mutate_at(vars(speeding:impaired_driver), as.integer) %>% 
  mutate_at(vars(speeding:impaired_driver), as.logical) %>% 
  mutate_if(is.character, factor) %>% 
  mutate_if(is.logical, as.factor) %>%
  mutate(crash_year = crash_year -  2004,
         fatalities_per_persons = fatal_count / person_count) %>%
  select(-c(fatal_count, injury_count, person_count)) %>% 
  #filter(fatalities_per_persons) %>% 
  na.omit() -> df_model_3

glimpse(df_model_3)
```

```{r}
model_3 <- rpart(fatalities_per_persons ~ ., 
                 control = rpart.control(cp = .005),
                 data = df_model_3)
model_3_output <- predict(model_3, newdata = df_model_3)
head(model_3_output)
```
```{r}
df_model_3 %>% 
  mutate(.pred = model_3_output, 
         .resid = .pred - fatalities_per_persons) %>% 
  select(fatalities_per_persons, .pred, .resid, everything()) -> df_model_3
df_model_3
```
```{r}
prp(model_3)
tidy(model_3)
summary(model_3)
```
```{r}
df_model_3 %>% 
  ggplot(aes(.pred, fatalities_per_persons)) +
  geom_jitter(alpha = .6) +
  geom_smooth()
```