---
title: "exploratory_crash_worksheet"
author: "Conor Tompkins"
date: "4/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)
```

```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(lubridate)
library(viridis)
library(ggmap)
library(broom)

theme_set(theme_bw(base_size = 18))

options(scipen = 999, digits = 4)
```



```{r}
read_csv("https://raw.githubusercontent.com/conorotompkins/allegheny_crashes/master/data/all-crashes2004-2016.csv") %>% 
  clean_names() %>% 
  mutate(crash_month = month(as.integer(crash_month), label = TRUE),
         day_of_week = wday(as.integer(day_of_week), label = TRUE),
         day_of_week = fct_shift(day_of_week, n = 1),
         time_of_day = as.integer(time_of_day),
         hour_of_day = as.integer(hour_of_day)) -> df
```
```{r}
preview <- skim(df)
```

```{r}
df %>% 
  distinct(crash_year)

df %>% 
  count(crash_year) %>% 
  ggplot(aes(crash_year, n)) +
    geom_line()
```

```{r}
df %>% 
  distinct(crash_month)

df %>% 
  count(crash_year, crash_month) %>% 
  ggplot(aes(crash_year, crash_month, fill = n)) +
    geom_tile() +
    coord_equal() +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_discrete(expand = c(0,0)) +
    scale_fill_viridis() +
    theme(panel.grid = element_blank())
```

```{r}
df %>% 
  ggplot(aes(hour_of_day)) +
  geom_histogram()

df %>% 
  mutate(day_of_week = fct_rev(day_of_week)) %>% 
  filter(!hour_of_day > 24,
         !is.na(day_of_week)) %>% 
  count(day_of_week, hour_of_day) %>% 
  ggplot(aes(hour_of_day, day_of_week, fill = n)) +
  geom_tile() +
  coord_equal() +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_viridis()
```

```{r}
df %>% 
  filter(!time_of_day > 2400,
         !is.na(day_of_week)) %>% 
  ggplot(aes(time_of_day, color = day_of_week)) +
  geom_freqpoly()
```

```{r}
df %>% 
  ggplot(aes(speed_limit)) +
  geom_freqpoly()
```

```{r}
df %>%
  count(speed_limit, speeding_related) %>% 
  ggplot(aes(speed_limit, n, color = as.factor(speeding_related))) +
  geom_point()
```

```{r}
df %>% 
  ggplot(aes(as.integer(injury_or_fatal))) +
  geom_histogram()
```

```{r}
df %>%
  select(contains("fatal", "inj")) -> df_casualties

df_casualties %>% 
  ggplot(aes(fatal_count)) +
  geom_freqpoly() +
  geom_rug()

df_casualties %>% 
  ggplot(aes(as.logical(injury_or_fatal))) +
  geom_bar()
```

```{r}
colnames(df)

df %>% 
  select(crash_crn, illumination, weather, road_condition, urban_rural, location_type, rdwy_surf_type_cd, workers_pres, wet_road, snow_slush_road, icy_road, sudden_deer, train, trolley) %>% 
  gather(key = environmental_factor, value = environmental_measurement, -crash_crn) -> df_environmental_factors
```

```{r}
df_environmental_factors %>% 
  count(environmental_factor, environmental_measurement) %>% 
  ggplot(aes(x = environmental_measurement, y = n)) +
  geom_col() +
  facet_wrap(~environmental_factor,
             scale = "free",
             ncol = 3)
```

```{r}
colnames(df)

df %>% 
  select(crash_crn, total_units, person_count, vehicle_count, automobile_count, motorcycle_count, bus_count, small_truck_count, heavy_truck_count, suv_count, van_count, bicycle_count, fatal_count, injury_count, maj_inj_count, mod_inj_count, min_inj_count, unk_inj_deg_count, unk_inj_per_count, unbelted_occ_count, unb_death_count, unb_maj_inj_count, belted_death_count, belted_maj_inj_count, mcycle_death_count, mcycle_maj_inj_count, bicycle_death_count, bicycle_maj_inj_count, ped_count, ped_death_count, ped_maj_inj_count, comm_veh_count) %>% 
  gather(accident_metadata, measurement, -crash_crn) ->  df_accident_metadata
```

```{r}
df_accident_metadata %>% 
  count(accident_metadata, measurement) %>% 
  ggplot(aes(x = measurement, y = n)) +
  geom_col() +
  #geom_density() +
  facet_wrap(~accident_metadata,
             scales = "free",
             ncol = 4)
```


```{r}
map_pgh <- get_map("Pittsburgh, PA",
                   zoom = 11,
                   maptype = "toner",
                   source = "stamen")

map_pgh <- ggmap(map_pgh)
```

```{r}
map_pgh
```

```{r}
df %>% 
  select(dec_lat, dec_long, hour_of_day, day_of_week) %>% 
  filter(!is.na(hour_of_day),
         hour_of_day < 24) %>% 
  #count(hour_of_day, dec_lat, dec_long) %>% 
  filter(!is.na(dec_lat),
         !is.na(dec_long)) -> df_map
```

```{r}
map_pgh +
  stat_density_2d(data = df_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis()
```

```{r}
map_pgh +
  stat_density_2d(data = df_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis() +
  facet_wrap(~hour_of_day) +
  theme_void()
```

```{r}
map_pgh +
  stat_density_2d(data = df_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  scale_fill_viridis() +
  facet_wrap(~day_of_week) +
  theme_void()
```

```{r}
df %>% 
  mutate(casualties = fatal_count + injury_count,
         icy_road = as.logical(icy_road),
         speeding_related = as.logical(speeding_related),
         rear_end = as.logical(rear_end)) %>% 
  select(casualties, speeding_related, speed_limit, day_of_week, hour_of_day, icy_road, rear_end, dec_lat, dec_long) %>% 
  filter(casualties > 1) -> df_casualties_map

map_pgh +
  stat_density_2d(data = df_casualties_map, 
                  aes(dec_long, dec_lat,
                      fill = ..level..),
                  geom = "polygon",
                  alpha = .5) +
  #geom_point(data = df_casualties_map, aes(dec_long, dec_lat, size = log10(casualties), alpha = .001), color = "red") +
  scale_fill_viridis() +
  theme_void()
```