---
  title: "modeling_crash_data randomforest"
author: "Conor Tompkins"
date: "April 24, 2018"
output: html_document
---
  
  #Notes
  
  *change crash_year to years_since_2014
*need to deal with cyclical nature of hour
**use sin() and cos()
***xhour = sin(2pi * hour_of_day/24), yhour = cos(2pi * hour_of_day/24)



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = TRUE, warning = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(lubridate)
library(viridis)
library(ggmap)
library(broom)
library(modelr)
library(ranger)

theme_set(theme_bw(base_size = 18))

options(scipen = 999, digits = 4)
```

```{r}
source("https://raw.githubusercontent.com/conorotompkins/allegheny_crashes/master/scripts/03_clean_data.R")

df <- df_combined_allegheny_county_crash_data_2004_2017_cleaned
```


```{r}
df %>% 
  summarize_all(funs(sum(is.na(.)) / length(.))) %>% 
  gather(column_name, is_na) %>% 
  arrange(desc(is_na)) %>% 
  filter(is_na >= .1) %>% 
  mutate(column_name = fct_reorder(column_name, is_na)) %>% 
  ggplot(aes(column_name, is_na)) +
  geom_col() +
  coord_flip()

#colnames(df)
(df %>% 
  select(fatal, crash_year, day_of_week, hour_of_day, weather, illumination, road_condition, collision_type, relation_to_road, urban_rural, person_count, vehicle_count, contains("driver"),
         speed_limit, speeding, cell_phone, alcohol_related, drinking_driver, aggressive_driving, fatigue_asleep, running_red_lt, running_stop_sign, tailgating, cross_median, impaired_driver)  %>% 
  mutate(crash_year = crash_year -  2004,
         fatal = as.integer(fatal),
         fatal = as.factor(fatal)) %>% 
  na.omit() -> df_model)
```

```{r}
crash_rf <- ranger(fatal ~ ., 
                   data = df_model,
                   importance = "impurity",
                   num.trees = 500)
```
```{r}
importance(crash_rf) %>% 
  tidy() %>% 
  arrange(desc(x)) %>% 
  mutate(names = fct_reorder(names, x)) %>% 
  ggplot(aes(names, x)) +
  geom_col() +
  coord_flip()
summary(crash_rf)
crash_rf$prediction.error
```

```{r}
df_model %>% 
  mutate(pred = predictions(crash_rf)) -> df_model
```

```{r}
df_model %>% 
  count(fatal, pred, sort = TRUE) %>% 
  ggplot(aes(fatal, pred, fill = n)) +
  geom_tile() +
  scale_fill_viridis()
```

```{r}
library(rattle)
fancyRpartPlot(t$finalModel)
```


